name: Ubuntu Latest

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install xrdp
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
    - name: Configure firewall
      run: |
        sudo ufw allow 3389/tcp
        sudo ufw --force enable
    - name: Set up user with password
      run: |
        sudo useradd -m -s /bin/bash rdpuser
        echo "rdpuser:P@ssw0rd!" | sudo chpasswd
        sudo adduser rdpuser sudo
    - name: Configure xrdp to use new user
      run: |
        sudo sed -i 's/^allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
    - name: Start xrdp service
      run: sudo systemctl start xrdp
    - name: Create Tunnel
      run: ./ngrok tcp 3389
